name: Build and Attest

on:
  push:
    branches: [ "main", "1.13" ]
  pull_request:
    branches: [ "main", "1.13" ]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Build Preparation (build.py)
      run: python build.py
      
    - name: Build with PyInstaller
      run: pyinstaller --noconfirm MediaTools.spec
      
    - name: Archive build artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Compress-Archive -Path dist\MediaTools -DestinationPath pyMediaTools-Windows.zip
        
    - name: Archive build artifacts (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd dist && zip -r ../pyMediaTools-macOS.zip MediaTools.app
        
    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: pyMediaTools-Windows
        path: pyMediaTools-Windows.zip

    - name: Upload Artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: pyMediaTools-macOS
        path: pyMediaTools-macOS.zip

  attest:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: pyMediaTools-Windows
        path: ./artifacts
        
    - name: Download macOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: pyMediaTools-macOS
        path: ./artifacts
        
    - name: Generate Source Provenance for Windows Artifact
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: "./artifacts/pyMediaTools-Windows.zip"

    - name: Generate Source Provenance for macOS Artifact
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: "./artifacts/pyMediaTools-macOS.zip"
